version: "3.9"

services:

  db:
    image: postgres:15-alpine
    container_name: dentalpin-db

    restart: unless-stopped

    environment:
      POSTGRES_DB: dental_clinic
      POSTGRES_USER: dental
      POSTGRES_PASSWORD: Bokloz55

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dental -d dental_clinic"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - yahia-net



  backend:
    build:
      context: ./backend

    container_name: dentalpin-backend

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql+asyncpg://dental:Bokloz55@db:5432/dental_clinic
      SECRET_KEY: Bokloz55
      ENVIRONMENT: development
      ALLOWED_ORIGINS: "*"
      STORAGE_BACKEND: local
      STORAGE_LOCAL_PATH: /app/storage

    ports:
      - "8040:8000"

    volumes:
      - storage_data:/app/storage

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    networks:
      - yahia-net



  frontend:
    build:
      context: ./frontend

    container_name: dentalpin-frontend

    restart: unless-stopped

    depends_on:
      - backend

    environment:
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
      NUXT_PUBLIC_API_BASE_URL: http://localhost:8040

    ports:
      - "3000:3000"

    command: npm run dev

    networks:
      - yahia-net



volumes:
  pgdata:
  storage_data:



networks:
  yahia-net:
    external: true
